config/routes.rb
AveenoFacebookApp::Application.routes.draw do
  
  devise_for :administrators
  root :to => 'results#landing_page'
  match '/admin' => 'results#index'
  match '/auth/:provider/callback' => 'results#display'
  match '/results/reveal_coupon_action' => 'results#reveal_coupon_action'
  match '/results/display' => 'results#display'
  resources :galleryimages
  resources :results
  resources :authentications
  
  
  
  

  

end

app/models/galleryimage.rb
class Galleryimage < ActiveRecord::Base
  has_attached_file :item
  has_attached_file :titleimage
  
end

app/controllers/galleryimages_controller.rb
class GalleryimagesController < ApplicationController
  # GET /galleryimages
  # GET /galleryimages.json
  def index
    @galleryimages = Galleryimage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleryimages }
    end
  end

  # GET /galleryimages/1
  # GET /galleryimages/1.json
  def show
    @galleryimage = Galleryimage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @galleryimage }
    end
  end

  # GET /galleryimages/new
  # GET /galleryimages/new.json
  def new
    @galleryimage = Galleryimage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @galleryimage }
    end
  end

  # GET /galleryimages/1/edit
  def edit
    @galleryimage = Galleryimage.find(params[:id])
  end

  # POST /galleryimages
  # POST /galleryimages.json
  def create
    @galleryimage = Galleryimage.new(params[:galleryimage])

    respond_to do |format|
      if @galleryimage.save
        format.html { redirect_to @galleryimage, notice: 'Galleryimage was successfully created.' }
        format.json { render json: @galleryimage, status: :created, location: @galleryimage }
      else
        format.html { render action: "new" }
        format.json { render json: @galleryimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleryimages/1
  # PUT /galleryimages/1.json
  def update
    @galleryimage = Galleryimage.find(params[:id])

    respond_to do |format|
      if @galleryimage.update_attributes(params[:galleryimage])
        format.html { redirect_to @galleryimage, notice: 'Galleryimage was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @galleryimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleryimages/1
  # DELETE /galleryimages/1.json
  def destroy
    @galleryimage = Galleryimage.find(params[:id])
    @galleryimage.destroy

    respond_to do |format|
      format.html { redirect_to galleryimages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/galleryimages_helper.rb
module GalleryimagesHelper
end

app/views/galleryimages/_form.html.erb
<%= form_for(@galleryimage) do |f| %>
  <% if @galleryimage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@galleryimage.errors.count, "error") %> prohibited this galleryimage from being saved:</h2>

      <ul>
      <% @galleryimage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label 'Image' %> <%= @galleryimage.item.url %><br />
    <%= f.file_field :item %>
  </div><br/>
 <div class="field">
    <%= f.label 'Title Image' %> <%= @galleryimage.titleimage.url %><br />
    <%= f.file_field :titleimage %>
  </div><br/>
 <div class="field">
    <%= f.label 'Share Icon Image URL' %><br />
    <%= f.text_area :copy %>
  </div><br/>

  
 <div class="field">
    <%= f.label 'Facebook Share Image URL' %><br />
    <%= f.text_area :fb_link %>
  </div><br/>
 <div class="field">
    <%= f.label 'Facebook Title' %><br />
    <%= f.text_field :fb_title %>
  </div><br/>
 <div class="field">
    <%= f.label 'Facebook Copy' %><br />
    <%= f.text_area :fb_copy %>
  </div><br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleryimages/edit.html.erb
<h1>Editing galleryimage</h1>

<%= render 'form' %>

<%= link_to 'Show', @galleryimage %> |
<%= link_to 'Back', galleryimages_path %>

app/views/galleryimages/index.html.erb
<h1>Listing Gallery Images</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    
  </tr>

<% @galleryimages.each do |galleryimage| %>
  <tr>
    <td><%= image_tag galleryimage.item.url %></td>
      <td><%= link_to 'Edit', edit_galleryimage_path(galleryimage)   %></td>

    <td><%= link_to 'Delete', galleryimage, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery Image', new_galleryimage_path %>

app/views/galleryimages/new.html.erb
<h1>New galleryimage</h1>

<%= render 'form' %>

<%= link_to 'Back', galleryimages_path %>

app/views/galleryimages/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_galleryimage_path(@galleryimage) %> |
<%= link_to 'Back', galleryimages_path %>