config/routes.rb
AveenoFacebookApp::Application.routes.draw do
  
  devise_for :administrators
  root :to => 'results#landing_page'
  match '/admin' => 'results#index'
  match '/auth/:provider/callback' => 'results#display'
  match '/results/reveal_coupon_action' => 'results#reveal_coupon_action'
  match '/results/display' => 'results#display'
  resources :galleryimages
  resources :results
  resources :authentications
  
  
  
  

  

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
   validates :name, :presence => true
   validates :what_it_means, :presence => true
   validates :friends_and_family, :presence => true
   validates :in_nature, :presence => true
   validates :beautiful_change_idea, :presence => true
   validates :product_title, :presence => true
   validates :product_description, :presence => true
   
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  # GET /authentications
  # GET /authentications.json
  def index
    @authentications = Authentication.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authentications }
    end
  end

  # GET /authentications/1
  # GET /authentications/1.json
  def show
    @authentication = Authentication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authentication }
    end
  end

  # GET /authentications/new
  # GET /authentications/new.json
  def new
    @authentication = Authentication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authentication }
    end
  end

  # GET /authentications/1/edit
  def edit
    @authentication = Authentication.find(params[:id])
  end

  # POST /authentications
  # POST /authentications.json
  def create
       #@facebook_response = JSON.parse(request.env["omniauth.auth"].to_json) 
    @birthday = Date.strptime(request.env["omniauth.auth"]["extra"]["raw_info"]["birthday"], "%m/%d/%Y").month if request.env["omniauth.auth"]["extra"]["raw_info"]["birthday"].present?
    #  response = Net::HTTP.get_response("example.com","/?search=thing&format=json")
    
    
 
   
      @output = case
      when @birthday == 1
	"January result -- Calming Feverfew"
      when @birthday == 2
	"February result -- Protective Lotus"
      when @birthday == 3
	"March result -- Balancing Seaweed Extract"
      when @birthday == 4
	"April result -- Revitalizing Shiitake Mushroom"
      when @birthday == 5
	"May result -- Strengthening Southernwood"
      when @birthday == 6
	"June result -- Revitalizing Shiitake Mushroom"
      when @birthday == 7
	"July result -- Protective Lotus"
      when @birthday == 8
	"August result -- Vibrant Lupine"
      when @birthday == 9
	"September result -- Nurturing Oat"
      when @birthday == 10
	"October result -- Resilient Soy"
      when @birthday == 11
	"November result -- Balancing Seaweed Extract"
      when @birthday == 12
	"December result -- Focusing Wheat"
      else
	"Nurturing Oat -- Nurturing Oat"
      end
      
      
  #  render :text => request.env["omniauth.auth"].to_yaml
    
   render :text => @output
  
   # post to wall code below
   # redirect_to 'https://graph.facebook.com/' + request.env["omniauth.auth"]["uid"] + '/feed?access_token=' + request.env["omniauth.auth"]["credentials"]["token"] + '&message=apptest_tony'
    
   
  end

  # PUT /authentications/1
  # PUT /authentications/1.json
  def update
    @authentication = Authentication.find(params[:id])

    respond_to do |format|
      if @authentication.update_attributes(params[:authentication])
        format.html { redirect_to @authentication, notice: 'Authentication was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication = Authentication.find(params[:id])
    @authentication.destroy

    respond_to do |format|
      format.html { redirect_to authentications_url }
      format.json { head :ok }
    end
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= form_for(@authentication) do |f| %>
  <% if @authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% @authentication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<h1>Listing authentications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authentications.each do |authentication| %>
  <tr>
    <td><%= authentication.user_id %></td>
    <td><%= authentication.provider %></td>
    <td><%= authentication.uid %></td>
    <td><%= link_to 'Show', authentication %></td>
    <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
    <td><%= link_to 'Destroy', authentication, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<div>
What that means
<hr/>
You are solution oriented and thrive in situations where a remedy is desired. You emphasize the
positive aspects of any circumstance. You are a true giver who finds a genuine sense of satisfaction
in helping others. Oat is also extremely trustworthy and is great at absorbing and containing a secret.
 You are hardworking and have a love of knowledge and know-how.
</div>
<div>
Friends and Family
<hr/>

</div>


<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>