config/routes.rb
AveenoFacebookApp::Application.routes.draw do
  
  devise_for :administrators
  root :to => 'results#landing_page'
  match '/admin' => 'results#index'
  match '/auth/:provider/callback' => 'results#display'
  match '/results/reveal_coupon_action' => 'results#reveal_coupon_action'
  match '/results/display' => 'results#display'
  resources :galleryimages
  resources :results
  resources :authentications
  
  
  
  

  

end

app/models/result.rb
class Result < ActiveRecord::Base
    has_attached_file :background
    has_attached_file :product
    has_attached_file :header
    has_attached_file :whatthatmeansheading
    has_attached_file :friendsandfamilyheading
    has_attached_file :innatureheading
    has_attached_file :beautifulchangeideaheading
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_filter :authenticate_administrator!, :except => ['display', 'landing_page']
 
  layout 'results'
  
  
  # GET /results
  # GET /results.json
  def index
    @results = Result.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @results }
    end
  end

  # GET /results/1
  # GET /results/1.json
  def show
    @result = Result.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end
  end
  
  
  def landing_page
    @images = Galleryimage.find(:all)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end
  end
  
  def reveal_coupon_action
      if params.has_key?(:post_id)
	cookies[:revealed_coupon] = 'true'  
	session[:revealed_coupon] = 'true'
      end
      redirect_to '/auth/facebook'
  end

  
  
  
  # GET /results/1
  # GET /results/1.json
  def display
      #  response = Net::HTTP.get_response("example.com","/?search=thing&format=json")
     if params.has_key?(:testmonth) # for testing
       @birthday = params[:testmonth].to_i
     else # naturally occuring case
       @birthday = Date.strptime(request.env["omniauth.auth"]["extra"]["raw_info"]["birthday"], "%m/%d/%Y").month if request.env["omniauth.auth"]["extra"]["raw_info"]["birthday"].present?
     end
   
      @output = case
      when @birthday == 1
	"Calming Feverfew"
      when @birthday == 2
	"Protective Lotus"
      when @birthday == 3
	"Balancing Seaweed Extract"
      when @birthday == 4
	"Revitalizing Shiitake"
      when @birthday == 5
	"Fortifying Southernwood"
      when @birthday == 6
	"Revitalizing Shiitake"
      when @birthday == 7
	"Protective Lotus"
      when @birthday == 8
	"Vibrant Lupine"
      when @birthday == 9
	"Nurturing Oat"
      when @birthday == 10
	"Resilient Soy"
      when @birthday == 11
	"Balancing Seaweed Extract"
      when @birthday == 12
	"Focused Wheat"
      else
	"Nurturing Oat"
      end
    @result = Result.find_by_name(@output)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end
  end

  
  
  # GET /results/new
  # GET /results/new.json
  def new
    @result = Result.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(params[:result])

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render json: @result, status: :created, location: @result }
      else
        format.html { render action: "new" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.json
  def update
    @result = Result.find(params[:id])

    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :ok }
    end
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result, :html => {:multipart => true}) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :what_that_means %><br />
    <%= f.text_area :what_that_means %>
  </div>
  <div class="field">
    <%= f.label :friends_and_family %><br />
    <%= f.text_area :friends_and_family %>
  </div>
  <div class="field">
    <%= f.label :in_nature %><br />
    <%= f.text_area :in_nature %>
  </div>
  <div class="field">
    <%= f.label :beautiful_change_idea %><br />
    <%= f.text_area :beautiful_change_idea %>
  </div>
  <div class="field">
    <%= f.label :product_title %><br />
    <%= f.text_field :product_title %>
  </div>
  <div class="field">
    <%= f.label :product_description %><br />
    <%= f.text_area :product_description %>
  </div>
   <div class="field">
    <%= f.label :facebook_subject %><br />
    <%= f.text_field :facebook_subject %>
  </div>


  <div class="field">
    <%= f.label :facebook_copy %><br />
    <%= f.text_area :facebook_copy %>
  </div>
  <div class="field">
    <%= f.label :fb_share_image_link %><br />
    <%= f.text_area :fb_share_image_link %>
  </div>
 <div class="field">
    <%= f.label :product_link %><br />
    <%= f.text_area :product_link %>
  </div>

   <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>


 <div class="field">
    <%= f.label 'Background Image' %> <%= @result.background.url %><br />
    <%= f.file_field :background %>
  </div><br/>
 <div class="field">
    <%= f.label 'Product Image' %> <%= @result.product.url %><br />
    <%= f.file_field :product %>
  </div><br/>
<div class="field">
    <%= f.label 'What That Means Header' %> <%= @result.whatthatmeansheading.url %><br />
    <%= f.file_field :whatthatmeansheading %>
  </div><br/>
<div class="field">
    <%= f.label 'Friends And Family Header' %> <%= @result.friendsandfamilyheading.url %><br />
    <%= f.file_field :friendsandfamilyheading %>
  </div><br/>
<div class="field">
    <%= f.label 'In Nature Header' %> <%= @result.innatureheading.url %><br />
    <%= f.file_field :innatureheading %>
  </div><br/>
<div class="field">
    <%= f.label 'Beautiful Change Idea Header' %> <%= @result.beautifulchangeideaheading.url %><br />
    <%= f.file_field :beautifulchangeideaheading %>
  </div><br/>
 <div class="field">
    <%= f.label 'Product Image horizontal offset' %> <br />
    <%= f.text_field :product_image_xoffset %>
  </div><br/>
  <div class="field">
    <%= f.label 'Product Image vertical offset' %> <br />
    <%= f.text_field :product_image_yoffset %>
  </div><br/>

<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/display.html.erb
<script src="//connect.facebook.net/en_US/all.js"></script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29838818-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<div id="fb-root-wrapper">
<div id="fb-root"></div>
</div>
<script>
// now buggy by Facebook API
// FB.UIServer.Methods["feed"].size = {width:450, height:270};

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '400302213341521', // App ID
      channelUrl : '//<%= request.host_with_port %>/channel.html', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });
    FB.Canvas.setSize({ height: 1150 });
    window.fbAsyncInit = function () {
      FB.Canvas.setAutoResize();
    }
    // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>
<script>
function initiate_feed() 
{
FB.ui(
  {
   method: 'feed',
   message: 'Facebook Connect',
   name: '<%= escape_javascript(@result.facebook_subject) if @result.facebook_subject.present?  %>',
   description: '<%= escape_javascript(@result.facebook_copy) if @result.facebook_copy.present? %>',
   link: 'http://www.be-an-active-natural.com/',
   picture: '<%= escape_javascript(@result.fb_share_image_link) if @result.fb_share_image_link.present? %>',
   actions: [
        { name: 'Aveeno® Profile Scanner', link: 'http://www.be-an-active-natural.com/' }
   ],
  user_message_prompt: 'This message prompt'
  },
  function(response) {
    if (response && response.post_id) {
      toggle_coupon();
    } else {
      //alert('Post was not published.');
    }
  }
);
}
</script>
<div id="result_content_wrapper" style="background-image: url('<%= @result.background.url %>');">
  <div id="result_header">
   
  </div>
  <div id="result_content">
    
    <div id="what_that_means">
      <h2 style="color: <%= @result.color %>"><%= image_tag @result.whatthatmeansheading.url %></h2>
      <hr/>
      <%= @result.what_that_means.html_safe %>
    </div>

    <div id="friends_and_family">
      <h2 style="color:  <%= @result.color %>"><%= image_tag @result.friendsandfamilyheading.url %></h2>
      <hr/>
      <%= @result.friends_and_family.html_safe %>
    </div>

    <div id="in_nature">
      <h2 style="color:  <%= @result.color %>"><%= image_tag @result.innatureheading.url %></h2>
      <hr/>
      <%= @result.in_nature.html_safe %>
    </div>

    <div id="beautiful_change_idea">
      <h2 style="color:  <%= @result.color %>"><%= image_tag @result.beautifulchangeideaheading.url %></h2>
      <hr/>
      <%= @result.beautiful_change_idea.html_safe %>
    </div>
   
         <div id="coupon">
  
	<h3>THANKS FOR SHARING YOUR ACTIVE NATURAL SIDE!</h3>
	<hr/><b>Click here</b> for $1 off our AVEENO® PURE RENEWEL&#153; Hair Care Collection
	  <br/>
	  <a id="redeemnow" href="http://www.ddb01.com/Dipal/aveeno_coupon/index.php" target="_blank" onClick="_gaq.push(['_trackEvent','Results', 'click_redeem_coupon']); "><img src="/Redeem_now.png" border="0"/></a><a href="/" id="goback" onClick="_gaq.push(['_trackEvent','Results', 'click_back']); ">< Go Back</a>
      </div>
     
<div><a id="facebook_dialog_link" onclick="initiate_feed();_gaq.push(['_trackEvent','Results', 'share_results_low']);"><img src="/ShareYourStory.png" border="0"  /></a></div>
    

    <div id="product_area">
      <h3>PRODUCTS FEATURING YOUR ACTIVE NATURALS<sup>&reg;</sup> INGREDIENT </h3>
      <hr/>
      <img id="product_image" style="left: <%= @result.product_image_xoffset %>px;top: <%= @result.product_image_yoffset %>px;" border="0" src="<%= @result.product %>" /> <span id="product_title"><%= @result.product_title.html_safe %></span>
	<div id="product_description">
	  <%= @result.product_description.html_safe %><br/><br/>
	  <a href="<%= @result.product_link %>" target="_blank" border="0"><img src="/Shop_Now.png" border="0"  onClick="_gaq.push(['_trackEvent','Results', 'click_show_now']); "></a>
	</div>
    </div>
  </div>
</div>

app/views/results/display_with_coupon.html.erb
<div id="result_content_wrapper" style="background-image: url('<%= @result.background.url %>');">
  <div id="result_header">
    <img src="<%= @result.header.url %>" />
  </div>
  <div id="result_content">
    

    <p>
      <h2 style="color: <%= @result.color %>">What That Means:</h2>
      <hr/>
      <%= @result.what_that_means.html_safe %>
    </p>

    <p>
      <h2 style="color:  <%= @result.color %>">Friends and Family:</h2>
      <hr/>
      <%= @result.friends_and_family.html_safe %>
    </p>

    <p>
      <h2 style="color:  <%= @result.color %>">In Nature:</h2>
      <hr/>
      <%= @result.in_nature.html_safe %>
    </p>

    <p>
      <h2 style="color:  <%= @result.color %>">Beautiful Change Idea:</h2>
      <hr/>
      <%= @result.beautiful_change_idea.html_safe %>
    </p>
    
    <a href="#" id="share_coupon_link"><img src="/Shop_Now.png" border="0" /></a>
    <div id="coupon">
      <h3>THANKS FOR SHARING YOUR ACTIVE NATURAL SIDE!</h3>
      <hr/>
      <b>Please enjoy $1 OFF</b> non-discounted items at <b>aveenostore.com<b/> with the following
	<b>promo code: BAAN2012</b><br/>
	<a href="http://www.aveenostore.com"><img src="/Redeem_now.png" /></a><a href="/index.html" id="goback">< Go Back</a>
    </div>
    <div id="product_area">
      <h3>PRODUCTS FEATURING YOUR ACTIVE NATURALS<sup>&reg;</sup> INGREDIENT </h3>
      <hr/>
      <img id="product_image" border="0" src="<%= @result.product %>" /> <h3><%= @result.product_title.html_safe %></h3>
	<div id="product_description">
	  <%= @result.product_description.html_safe %><br/>
	  <a href="http://www.aveenostore.com"><img src="/Shop_Now.png"></a>
	</div>
    </div>
  </div>
</div>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Site Administration</h1>
<br/>
[ <%= link_to('Logout', destroy_administrator_session_path, :method => :delete) %>    ]

<br/>


<div><br/><br/><br/>

Preview:
<% (1..12).each do |month_index| %>
  <a href="/results/display?testmonth=<%= month_index %>">[ <%= Date::MONTHNAMES[month_index] %> ]</a> &nbsp;
<% end %>
</div>
<br/><br/><br/>

[ <%= link_to 'Image Gallery', galleryimages_url %> ]

<br/><br/><br/>

<table>
  <tr>
    <th>Name</th>
    <th>What that means</th>
    <th>Friends and family</th>
    <th>In nature</th>
    <th>Beautiful change idea</th>
    <th>Product title</th>
    <th>Product description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr>
    <td><%= result.name %></td>
    <td><%= result.what_that_means %></td>
    <td><%= result.friends_and_family %></td>
    <td><%= result.in_nature %></td>
    <td><%= result.beautiful_change_idea %></td>
    <td><%= result.product_title %></td>
    <td><%= result.product_description %></td>
    <td><%= link_to 'Show', result %></td>
    <td><%= link_to 'Edit', edit_result_path(result) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/results/landing_page.html.erb
<html>
<head>
<link rel="stylesheet" type="text/css" href="/assets/application.css" />
<link rel="stylesheet" type="text/css" href="/assets/skin.css" />


<script src="/assets/index.js" ></script>
<script src="/assets/jquery.jcarousel.min.js"></script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29838818-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script type="text/javascript">
// initialize the carousel

$(document).ready(function() {
	//FB.login();
      $('#our_commitment_gallery').jcarousel({
		visible: 1,
		scroll: 1,
		initCallback: mycarousel_initCallback,
		itemLoadCallback: newVisibleItemCallback,
		buttonNextHTML: null,
		buttonPrevHTML: null
	});

      // data for carousel
     $.data(document.body, 'current_fb_name', '');
     $.data(document.body, 'current_fb_description', '');
     $.data(document.body, 'current_fb_link', '');

     
});


function mycarousel_initCallback(carousel)
{
	$('img#navigate-right').click(function() {
		_gaq.push(['_trackEvent','Landing Page', 'click_image_right',$.data(document.body, 'current_fb_name')]);
		carousel.next();
		
	});
		
	$('img#navigate-left').click(function() {
		_gaq.push(['_trackEvent','Landing Page', 'click_image_left',$.data(document.body, 'current_fb_name')]);	
		carousel.prev();
		
	});

	 $('img#gallery_header').attr("src", $(".jcarousel-item").eq(carousel.first -1).children('img').attr("header_url"));
	$.data(document.body, 'current_fb_name', $(".jcarousel-item").eq(carousel.first - 1 ).children('img').attr("fb_title"));
	$.data(document.body, 'current_fb_description', $(".jcarousel-item").eq(carousel.first - 1 ).children('img').attr("fb_description"));
	$.data(document.body, 'current_fb_link', $(".jcarousel-item").eq(carousel.first - 1 ).children('img').attr("fb_link"));
	$.data(document.body, 'current_fb_share_icon', $(".jcarousel-item").eq(carousel.first - 1 ).children('img').attr("icon_link"));
  	
}

function newVisibleItemCallback(carousel, item)
{
 // console.log($(".jcarousel-item").eq(carousel.first).attr("src"));
 // console.log($(".jcarousel-item").eq(carousel.first  -1).children('img').attr("src"));
  //console.log($(".jcarousel-item").eq(carousel.first - 1 ).children('img').attr("header_url"));
  //console.log(carousel.first);
  $('img#gallery_header').attr("src", $(".jcarousel-item").eq(carousel.first -1).children('img').attr("header_url"));
   $.data(document.body, 'current_fb_name', $(".jcarousel-item").eq(carousel.first - 1 ).children('img').attr("fb_title"));
   $.data(document.body, 'current_fb_description', $(".jcarousel-item").eq(carousel.first - 1 ).children('img').attr("fb_description"));
   $.data(document.body, 'current_fb_link', $(".jcarousel-item").eq(carousel.first - 1 ).children('img').attr("fb_link"));
   $.data(document.body, 'current_fb_share_icon', $(".jcarousel-item").eq(carousel.first - 1 ).children('img').attr("icon_link"));
  
   if (carousel.first == 1)
     $('img#navigate-left').hide();
   else
       $('img#navigate-left').show();
   
   if (carousel.first == carousel.size())
     $('img#navigate-right').hide();
   else
     $('img#navigate-right').show();
}

</script>

</head>

<body>
<div id="fb-root-wrapper">
  <div id="fb-root"></div>
</div>

<script>

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '400302213341521', // App ID
      channelUrl : '//<%= request.host_with_port %>/channel.html', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });
   FB.Canvas.setSize({ height: 2350 });    
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>
<script>

function initiate_feed() {
//FB.UIServer.Methods["feed"].size = {width:450, height:270};
//scroll = $(window).scrollTop();

//window.scrollTo(scroll+500);
FB.ui(
  {
   method: 'feed',
   message: 'Facebook Connect',
   name: eval("unescape($.data(document.body, 'current_fb_name').toString());"),
   description: eval("unescape($.data(document.body, 'current_fb_description').toString());"),
   /*link: eval("encodeURI($.data(document.body, 'current_fb_link').toString());") , */
   caption: '',
   link: 'http://www.facebook.com/aveeno',
   picture: eval("encodeURI($.data(document.body, 'current_fb_share_icon').toString());"),
   actions: [
        { name: 'Be an Active Natural', link: 'http://www.be-an-active-natural.com/' }
   ],
  user_message_prompt: 'This message prompt'
  },
  function(response) {
  }
);

}
</script>
<div id="content_wrapper">
  <img src="/BAAN_mission.png" id="our_mission_header" />
  <img src="/be_an_active.png" id="be_an_active_image"/>
  <div style="text-align:center; width:513px; margin-left:auto; margin-right:auto;">
    <img id="Image-Maps_2201203081508179" style="width: 493px; height: 450px;" src="/Profile_Scanner_frame1.gif" usemap="#Image-Maps_2201203081508179" border="0" width="513" height="481" alt="" 	/>
    <map id="_Image-Maps_2201203081508179" name="Image-Maps_2201203081508179">
      <area shape="rect" coords="165,232,351,266"  id="scan_profile_link" alt="" title="" onClick="_gaq.push(['_trackEvent','Landing Page', 'click_scan_now','Landing Page']);"   />
    </map>
    
    <img id="scanning" src="/pScannerAni.gif"/>
    <img src="/activeNaturalRings.png" id="active_natural_rings"/>

	<div>
	<img id="garden_image" src="/garden2.png" usemap="#Image-Maps_4201204052324459" border="0" width="515" height="414" alt="" />
	<map id="_Image-Maps_4201204052324459" name="Image-Maps_4201204052324459">
	<area shape="rect" coords="185,344,335,379" target="_top" href="https://www.facebook.com/aveeno/app_295805387151302" alt="" title=""  onClick="_gaq.push(['_trackEvent','Landing Page', 'click_learn_contest','Landing Page']);"  />
	</map>
	</div>
            

  </div>
  <div id="our_commitment">   <img src="/gallery_header.png" id="gallery_header" /><br/><img id="fb_share_btn" src="/bttn_share.png" onclick="initiate_feed(); _gaq.push(['_trackEvent','Landing Page', 'click_share_image', $.data(document.body, 'current_fb_name')]); return false;" /> 
      <div id="gallery_widget_box" class="jcarousel-skin-tango">
	<img src="/arrow_left.png" id="navigate-left" />
	  <ul id="our_commitment_gallery">
	    <% @images.each do |image| %>
	       <li>
		<img src="<%= image.item.url %>" header_url="<%= image.titleimage.url %>" icon_link="<%= image.copy %>" fb_link="<%=  URI.escape(image.fb_link) %>" fb_name="<%= URI.escape(image.fb_title) %>" fb_description="<%= URI.escape(image.fb_copy) %>" onClick="_gaq.push(['_trackEvent','Landing Page', 'click_image', $.data(document.body, 'current_fb_name')]);" />
	      </li>
	    <% end %>
	   
	  </ul>
	<img src="/arrow_right.png" id="navigate-right" />
      </div>
    </div>

  <img src="/footer.png" id="footer"/><br /><br/>
  <div id="legal" style="padding-left: 6px; padding-right: 6px;"><br/>
  No purchase necessary to enter or win. Void where prohibited. Must be a legal resident of the United States or the District of Columbia, 18 years of age or older as of date of Application. Program starts at 12:00 p.m. ET on 4/10/12 and ends at 12:00 p.m. ET on 10/31/12. Subject to Official Rules <a href="" onClick="window.open('https://aveenoactivenaturals.dja.com/common/rules.html','','scrollbars=yes,menubar=no,width=544,height=600,left=' + (window.width/2 - 277) + ',resizable=yes,toolbar=no,location=no,status=no');return false;" style="color: #76902b;">here</a>. Sponsor: Johnson & Johnson Consumer Products Company Division of Johnson & Johnson Consumer Companies, Inc.<br/><br/> 

© Johnson & Johnson Consumer Companies, Inc. 2012. This application is published by Johnson & Johnson Consumer Products Company Division of Johnson & Johnson Consumer Companies, Inc., which is solely responsible for its content. It is intended for visitors from the U.S. <br/><br/>

This Contest is in no way sponsored, endorsed or administered by, or associated with, Facebook.<br/>
You understand that you are providing your information to Johnson & Johnson Consumer Products<br/>
Company Division of Johnson & Johnson Consumer Companies, Inc. and not to Facebook.
<br/><br/>
 	<div id="legal_links">
   	<a href="" onClick="_gaq.push(['_trackEvent','Landing Page', 'click_rules','Landing Page']);window.open('https://aveenoactivenaturals.dja.com/common/rules.html','','scrollbars=yes,menubar=no,width=544,height=600,left=' + (window.width/2 - 277) + ',resizable=yes,toolbar=no,location=no,status=no');return false;">Official Rules</a>&nbsp;&nbsp;&nbsp;
	<a href="http://www.aveeno.com/privacy-policy" target="_blank" onClick="_gaq.push(['_trackEvent','Landing Page', 'click_privacy_policy']);">AVEENO&reg; Privacy Policy</a>&nbsp;&nbsp;&nbsp;
        <a href="http://www.aveeno.com/legal-notice" target="_blank" onClick="_gaq.push(['_trackEvent','Landing Page', 'click_legal_notice']);">AVEENO&reg; Legal Notice</a>&nbsp;&nbsp;&nbsp;
<a href="" onClick="_gaq.push(['_trackEvent','Landing Page', 'click_faqs','Landing Page']);window.open('https://aveenoactivenaturals.dja.com/common/faq.html','','scrollbars=yes,menubar=no,width=544,height=600,left=' + (window.width/2 - 277) + ',resizable=yes,toolbar=no,location=no,status=no');return false;">FAQs</a>&nbsp;&nbsp;&nbsp;

        </div>
 </div>
  
</div>


            
</body>
</html>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>


<% @result.attributes.each_pair do |name, value| %>
<p>
  <b><%= name %>:</b>
  <%= value %>
</p>
<% end %>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>